### ISSUE TITLE
minYear() کار نمی کند

### ISSUE THREAD

**Issue by mohammadrafigh** [alirezaafkar/SunDatePicker#10]
درود بر شما

متاسفانه ظاهرا minYear() به ازای مقادیر مختلفی که امتحان می کنم کار نمی کنه:

`new DatePicker.Builder()
                .id(1)
                .theme(R.style.DialogTheme)
                .date(new JDF())
                .minYear(1320)
                .maxYear(1450)
                .build(this)
                .show(getSupportFragmentManager(), "");`

maxYear مشکلی نداره و نتیجه درست میده.

**Comment by arminghm** [comment]
+1

**Comment by farbod-s** [comment]
@mohammadrafigh @arminghm @alirezaafkar 
in `/components/DateItem.java` line number `62` change:
``
public void setMinYear(int maxMonth) { this.minYear = minYear; }
``
to:
``
public void setMinYear(int minYear) { this.minYear = minYear; }
``

**Comment by alirezaafkar** [comment]
Fixed in new version
