### ISSUE TITLE
مشکل در انتخاب روز آخر سال کبیسه

### ISSUE THREAD

**Issue by afshin-hoseini** [alirezaafkar/SunDatePicker#15]
سلام، بابت کتابخانه عالی ای که طراحی کردید ممنونم. فقط یه مورد **خیلی** جزئی  پیدا کردم و فکر نمیکنم که ارزش تصحیح داشته باشه ولی واسه من پیش اومد. فقط واسه اطلاع میگم.
اگر روز ۳۰ اسفند ۹۵ انتخاب بشه و بعد سال رو به ۱۳۹۴ تغییر بدیم، همچنان روی ۳۰ اسفند باقی میمونه در حالی که اسفند ۹۴ بیست و نه روزه است.

**Comment by ali-habibi** [comment]
سلام جناب مهندس، من در انتخاب حداقل و حداکثر سالها مشکل دارم.

یک سوال :
من به این تابع هر مقداری میدم ، اعمال نمیشه...
**و فقط تقویم سال جاری را نمایش میدهد.**

dp.setYearRange(jdf.getIranianYear()-50, jdf.getIranianYear()+5)

از کجا باید حداقل و حداکثر سالها را معین کنم ، چون میخوام برای تاریخ تولد بکارگیرم.
بدجور نیاز دارم ، ممنون از راهنماییتون
