### ISSUE TITLE
تشکر و یک سوال 

### ISSUE THREAD

**Issue by ali-habibi** [alirezaafkar/SunDatePicker#16]
سلام جناب مهندس، ضمن تشکر از این نمونه کتابخونه ای که رایگان در اختیار کاربران قرار دادین.

یک سوال : 
 من به این تابع هر مقداری میدم ، اعمال نمیشه...
و فقط تقویم سال جاری را نمایش میدهد.

```
dp.setYearRange(jdf.getIranianYear()-50, jdf.getIranianYear()+5)
```

از کجا باید حداق و حداکثر سالها را معین کنم ، چون میخوام برای تاریخ تولد بکارگیرم.
بدجور نیاز دارم ، ممنون از راهنماییتون.

**Comment by alirezaafkar** [comment]
سلام،
روی سال کلیک کنید سال‌ها نمایش داده میشن.
اگر این کار رو می‌کنید و همچنان مشکل حل نشده کد + عکس بذارید.

**Comment by ali-habibi** [comment]
سلام مهندس عزیز،
خیلی ممنون از راهنمایتون..

بله درست شد، من بخاطر محدودیت صفحه خودم سال و ماه را برداشته بودم...
و فکر میکردم ، با حرکت اسلاید تغییر میکنه...

ولی یک مشکل کوچولو که هست وقتی کد زیر را در نظر میگیرم :

dp.setYearRange(jdf.getIranianYear()-45, jdf.getIranianYear())

حالا وقتی که مثلا کاربر اشتباها تاریخ 1-1-69 را ست میکنه.

و دوباره برمیگرده که درستش کنه دیگه از سال 1369 جلوتر نمیره.

چون من این را برای سال تولد در نظر گرفتم.

لذاخوب نیست که کد زیر را قرار بدم...

dp.setYearRange(jdf.getIranianYear()-45, jdf.getIranianYear()+45)

که باز هم این 45 تا به سالی که تازه انتخاب شده (set) اضافه میکنه.

در حالی که بایستی 45 تا به سال جاری اضافه کنه.




‫در ۱۷ تیر ۱۳۹۵ ه‍.ش.، ساعت ۱:۱۰‏، Alireza Afkar‏ <notifications@github.com>
نوشت:‏

> سلام،
> روی سال کلیک کنید سال‌ها نمایش داده میشن.
> اگر این کار رو می‌کنید و همچنان مشکل حل نشده کد + عکس بذارید.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alirezaafkar/SunDatePicker/issues/16#issuecomment-230907836>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATNKzMN7_2KqkEN92lA5fmAUMko8gyVeks5qTBnEgaJpZM4JGSvO>
> .
>



-- 

*--------------------------در پناه حق...*

**Comment by alirezaafkar** [comment]
شما اگر یکبار DatePicker رو بسازید لازم نیست هربار بسازید
یا به روش زیر عمل کنید

JDF j = new JDF();
dp.setYearRange(j.getIranianYear()-45, j.getIranianYear()+45)

**Comment by ali-habibi** [comment]
ابتدا عذرخواهی بنده را بخاطر جسارتم بپذیرید و نیتم جز حل مشکل خودم نیست.

و اما مثل اینکه نتونستم منظورم رو برسونم...
با توجه به کلیپ در فایل پیوست ....

با توجه به کد:

dp.setYearRange(jdf.getIranianYear() - 10, jdf.getIranianYear()+10)

مثلا کاربر میخواهد سال تولد خود را انتخاب کند، وقتی میرود لیست سال ها و
میرود پایین تا سال 1405 پیش میره 😄
که این خوب نیست...

و حال با توجه به کد:

dp.setYearRange(jdf.getIranianYear() - 10, jdf.getIranianYear())


 برفرض این که کاربر اشتباها سال تولد خود را *20-04-1385 *وارد کرده است، که
بعد از set کردن بار اول، دوباره میخواد بره لیست سالها فقط تا سال 1385 بر
میگرده و جلوتر نمیره در حالی که کاربر شاید میخواهد 1390 را انتخاب کند...

و من فقط یکی از این کدها را استفاده میکنم که مجبور با باگی که داره کنار بیام.

و البته اولی را ترجیح میدم.😄



2016-07-07 13:26 GMT+04:00 Alireza Afkar <notifications@github.com>:

> شما اگر یکبار DatePicker رو بسازید لازم نیست هربار بسازید
> یا به روش زیر عمل کنید
>
> JDF j = new JDF();
> dp.setYearRange(j.getIranianYear()-45, j.getIranianYear()+45)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alirezaafkar/SunDatePicker/issues/16#issuecomment-231028311>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATNKzGQEaDwHE82t340jAYOkOr7ALx90ks5qTMYtgaJpZM4JGSvO>
> .
>



-- 

*--------------------------در پناه حق...*

**Comment by alirezaafkar** [comment]
من واقعا مشکل شما رو متوجه نمی‌شم

**Comment by ali-habibi** [comment]
حالا زیاد مسئله مهمی نیست...

شاید هم من اشتباه میکنم.

خیلی ممنون از راهنماییهاتون...🙏😊

2016-07-10 9:09 GMT+04:00 Alireza Afkar <notifications@github.com>:

> من واقعا مشکل شما رو متوجه نمی‌شم
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alirezaafkar/SunDatePicker/issues/16#issuecomment-231571174>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATNKzP3C1OqaIH4vag-hZEgAGzTtVo9jks5qUH5_gaJpZM4JGSvO>
> .
>



-- 

*--------------------------در پناه حق...*
