### ISSUE TITLE
بدست آوردن نام روز در هفته

### ISSUE THREAD

**Issue by alisadri5890** [alirezaafkar/SunDatePicker#19]

**Comment by alisadri5890** [comment]
سلام
میخواستم به نام روز در هفته دسترسی پیدا کنم
مثلا روز انتخابی دوشنبه اس
و اینکه حداقل تاریخ رو بشه انتخاب کرد
یعنی از یه تاریخی به بعد کاربر بتونه تاریخ انتخاب کنه

**Comment by amirit67** [comment]
سلام ....
باید از تابع 
getDayName()
استفاده کنید
