### ISSUE TITLE
Library should support RTL, Even if i set the android:supportsRtl="false" in app manifest

### ISSUE THREAD

**Issue by mori-honest** [alirezaafkar/SunDatePicker#25]
For some reasons(I want to handle the RTLize process myself), I have to set `android:supportsRtl="false"` to my application manifest and also add `tools:replace="android:supportsRtl"` to manifest.

So, when I add the `SunDatePicker` to my project and show a picker dialog, the dialog layout is LTR and not so nice:

![screenshot from 2017-02-07 11-45-31](https://cloud.githubusercontent.com/assets/5219339/22682967/00e0772e-ed2b-11e6-806e-bde2421d9a44.png)

**Comment by alizarei95** [comment]
+1 same here
