### ISSUE TITLE
@Nullable Calendar calendar argument returned through callback method onDateSet is not accurate.

### ISSUE THREAD

**Issue by mostafahadian** [alirezaafkar/SunDatePicker#34]
Hi Alireza.

The argument `calendar` which is passed to the callback method `onDateSet `below, is not accurate.

```
public interface DateSetListener {
    void onDateSet(int id, @Nullable Calendar calendar, int day, int month, int year);
}
```

The method which is used to calculate the calendar argument, can be seen below.
The problem is that ` Calendar.getInstance()` by default has the current time of the device, and when you call the method `calendar.set(year, month, day)` it just sets the year, the month, and the day of calendar and leaves the time of the day unchanged. So every time you pick a date using the datepicker, the calendar instance returned through the callback method `onDateSet` contains a combination of the date chosen and the current time of the device. But it is expected to return the first millisecond of the date chosen.

```
    public Calendar getCalendar() {
        JDF jdf = new JDF();
        jdf.setIranianDate(year, month, day);
        Calendar calendar = Calendar.getInstance();
        calendar.set(jdf.getGregorianYear(),
                jdf.getGregorianMonth()-1,
                jdf.getGregorianDay());
        return calendar;
    }
```

You can test it by printing `calendar.getTimeInMillis()` after the date is chosen from datepicker and you will see that each time the number changes while choosing the same date.

Thanks for your nice library.

**Comment by omidheshmatinia** [comment]
Hi, When we talk about `date` it means the hour and minute is not important! 
If you need to get a calendar with zero hour and minute, just set it by yourself. @mostafahadian

**Comment by mostafahadian** [comment]
Hi,
Thanks for your reply.
It would be better to return a calendar instance which is stable if any is returned.
Imagine a developer wants to compare the two calendar instances returned by the method using the method `.equals()`. Then he will always get 1 or -1 and never get 0. It means that the `.equals` method will always say that the two instances are not equal even if the dates chosen are the same.
And to solve it, it is needed that the method set the time of the day and then return the calendar instance.
```
        calendar.set(Calendar.HOUR_OF_DAY, 0);
        calendar.set(Calendar.MINUTE, 0);
        calendar.set(Calendar.SECOND, 0);
        calendar.set(Calendar.MILLISECOND, 0);
```
This way, the instances of calendar returned, are stable and comparable and they are always at the first millisecond of the day.
