### ISSUE TITLE
مشکل راست به چپ دارد

### ISSUE THREAD

**Issue by yousefi1361** [alirezaafkar/SunDatePicker#36]
سلام داداشی ممنون 
من از کتابخانه شما استفاده کردم ولی شروع روز های هفته از سمت چپ است 
نمیشه کاری کرد تا از سمت راست شروع بشود ممنون 
خیلی باحالی

**Comment by alirezaafkar** [comment]
تو آخرین نسخه این مشکل باید حل شده باشه.
