### ISSUE TITLE
disable past?

### ISSUE THREAD

**Issue by mamalmaster** [alirezaafkar/SunDatePicker#37]
سلام، ممنون بابت این کتابخونه پرکاربرد، درحال حاضر امکان غیرفعال کردن آینده وجود داره اما امکان غیرفعال کردن گذشته نیست، اگر بگید چطور اینکار رو کنم ممنون میشم

**Comment by rezaiyan** [comment]
I'm done this feature in [this pull request](https://github.com/alirezaafkar/SunDatePicker/pull/38)

**Comment by alirezaafkar** [comment]
https://github.com/alirezaafkar/SunDatePicker/issues/40
