### ISSUE TITLE
Bahman 1397 has just 29 days

### ISSUE THREAD

**Issue by asr1994** [alirezaafkar/SunDatePicker#44]
Hi there and appreciate for your useful component , but why Bahman 1397 has 29 days. another problem is the year 1397 is not kind of Kabiseh and then Esfand has 30 days.

I'll be apreciate if you fix these issues

**Comment by alirezat66** [comment]
I get same bug just today.

**Comment by alirezat66** [comment]
> Hi there and appreciate for your useful component , but why Bahman 1397 has 29 days. another problem is the year 1397 is not kind of Kabiseh and then Esfand has 30 days.
> 
> I'll be apreciate if you fix these issues

have you solved your problem?

**Comment by alirezaafkar** [comment]
@alirezat66 @asr1994 Have you guys solved your problem?

**Comment by asr1994** [comment]
@alirezaafkar No sir, is there any solution for this issue?

**Comment by abbasalim** [comment]
این مشکل در سال 98 هم هست. و کاربران ما هم به مشکل خوردن.

**Comment by alirezaafkar** [comment]
Fixed.
