### ISSUE TITLE
تم دیالوگ در نسخه جدید

### ISSUE THREAD

**Issue by mahramane** [alirezaafkar/SunDatePicker#46]
سلام آقای افکار
کد های قبلی که داخل استایل تعریف کرده بودم برای نسخه جدید کتابخونه کار نمیکنه و تم دیالوگ رو تغییر نمیده من میخوام قسمت 
بالای دیالوگ رنگ دیگه ای باشه چطور این کار رو انجام بدم؟
باتشکر

**Comment by mohamadjavadx** [comment]
@mahramane  سلام من هم با تم مشکل دارم میخواستم بونم شما مشکلتون رو چطور حل کردید؟

**Comment by mahramane** [comment]
سلام
 من کتابخونه رو از گیت هاب دانلود کردم و به صورت دستی به پروژه اضافه کردم بعد تغییرات رو روی خود کتابخونه اعمال کردم

**Comment by mohamadjavadx** [comment]
(ممنون من هم با راه مشابه مشکلم حل شد (کتابخونه رو برسی کردم  و استایلی که به صورت پیشفرض استفاده میشد رو بازنویسی کردم
