### ISSUE TITLE
افزودن به gradle

### ISSUE THREAD

**Issue by abbasalim** [alirezaafkar/SunDatePicker#6]
به نام خدا
سلام آقا علیرضا کارتون خیلی قشنگه
فقط اگه میشه به گریدل اضافش کنی که راحت بتونیم داخل اندروید استودیو ازش استفاده کنیم. اینجوری سخته
ممنون

**Comment by alirezaafkar** [comment]
@abbasalim سلام.
بله در نسخه بعدی انجام خواهد شد.

**Comment by alirezaafkar** [comment]
@abbasalim انجام شد.
