### ISSUE TITLE
android:supportsRtl="false"

### ISSUE THREAD

**Issue by abbasalim** [alirezaafkar/SunDatePicker#9]
بنام خدا
سلام
وقتی 
android:supportsRtl="false"
اضافه کنم به پروژم این خطا رو میده از کتابخونه شما
`D:\work\tennis\app\src\main\AndroidManifest.xml:9:9-36 Error:
	Attribute application@supportsRtl value=(false) from AndroidManifest.xml:9:9-36
	is also present at [com.alirezaafkar:sundatepicker:2.0.0] AndroidManifest.xml:13:9-35 value=(true).
	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:8:5-25:19 to override.
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
:app:processDebugManifest FAILED
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@supportsRtl value=(false) from AndroidManifest.xml:9:9-36
	is also present at [com.alirezaafkar:sundatepicker:2.0.0] AndroidManifest.xml:13:9-35 value=(true).
	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:8:5-25:19 to override.`

**Comment by mj-developer** [comment]
یا مقدارش رو تورو بکن یا تو تگ اپلیکپشن تو مانیفست از این استفاده کن

tools:replace="android:supportsRtl"

مثل عکس

![1](https://cloud.githubusercontent.com/assets/13723955/17409869/47ea2260-5a86-11e6-907e-0c5b05970714.png)

**Comment by AhoraTeam** [comment]
hi, this is so late for you but maybe useful for others.
com.alirezaafkar:sundatepicker:2.0.0
just delete this library.

**Comment by El-barbri** [comment]
you want me create a new style after add tag "replace:" ??

**Comment by omidheshmatinia** [comment]
What do you mean by  adding new style ?! @El-barbri
